apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: sxajskj5g-python 
  janus-idp.io/tekton: sxajskj5g-python
  backstage.io/kubernetes-id: sxajskj5g-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sxajskj5g-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml